
import type { MainLocation, Entry, Department, User } from './types';

export const locations: MainLocation[] = [
  {
    id: 'ed-hyd-ro',
    name: 'ED-HYD-RO',
    descriptiveName: 'Corporate Office',
    macAddress: '00:1A:2B:3C:4D:5E',
    cardStart: 101,
    cardEnd: 200,
    subLocations: [],
  },
  {
    id: 'hyd-so',
    name: 'HYD-SO',
    descriptiveName: 'Software Office',
    macAddress: '00:1A:2B:3C:4D:5F',
    cardStart: 201,
    cardEnd: 300,
    subLocations: [],
  },
  {
    id: 'warehouse',
    name: 'WAREHOUSE',
    descriptiveName: 'Main Warehouse',
     macAddress: '00:1A:2B:3C:4D:6A',
    cardStart: 301,
    cardEnd: 400,
    subLocations: [],
  },
  {
    id: 'hostel',
    name: 'HOSTEL',
    descriptiveName: 'Company Hostel',
    macAddress: '00:1A:2B:3C:4D:9C',
    cardStart: 401,
    cardEnd: 450,
    subLocations: [],
  },
];

export const departments: Department[] = ['Supply Chain', 'Accounts', 'HR', 'Operations'];

export const defaultUsers: User[] = [
  {
    id: 'process-owner',
    role: 'process-owner',
    locationName: 'Process Owner',
    email: 'owner@example.com',
    password: 'password123',
    locationId: 'process-owner'
  },
];


export const mockData: Entry[] = [
  // Corporate Office - 1st Floor
  {
    id: '1',
    type: 'Visitor',
    name: 'Ananya Singh',
    mobile: '9988776655',
    email: 'ananya.singh@example.com',
    hostName: 'Sunita Reddy',
    hostDepartment: 'Supply Chain',
    reasonForVisit: 'Vendor Meeting',
    selfieUrl: 'https://picsum.photos/seed/ananya/100/100',
    checkInTime: new Date(new Date().setHours(9, 30, 0, 0)),
    status: 'Checked-in',
    location: { main: 'Corporate Office', sub: '1st Floor' },
    govtIdType: 'Aadhaar Card',
    visitorCardNumber: '101',
    visitorCardReturned: false,
  },
  {
    id: '2',
    type: 'Visitor',
    name: 'Sameer Jain',
    mobile: '9823456789',
    hostName: 'Sunita Reddy',
    hostDepartment: 'Supply Chain',
    reasonForVisit: 'Follow-up meeting',
    selfieUrl: 'https://picsum.photos/seed/sameer/100/100',
    checkInTime: new Date(new Date().setHours(14, 0, 0, 0)),
    status: 'Checked-in',
    location: { main: 'Corporate Office', sub: '1st Floor' },
    govtIdType: 'Driving Licence',
    visitorCardNumber: '102',
    visitorCardReturned: false,
  },
  {
    id: '4',
    type: 'Visitor',
    name: 'Neha Gupta',
    mobile: '9001234568',
    email: 'neha.gupta@example.com',
    hostName: 'Sunita Reddy',
    hostDepartment: 'Supply Chain',
    reasonForVisit: 'Partnership discussion',
    selfieUrl: 'https://picsum.photos/seed/neha/100/100',
    checkInTime: new Date(new Date().setHours(10, 0, 0, 0)),
    checkOutTime: new Date(new Date().setHours(11, 30, 0, 0)),
    status: 'Checked-out',
    location: { main: 'Corporate Office', sub: '1st Floor' },
    govtIdType: 'Passport',
    visitorCardNumber: '103',
    visitorCardReturned: true,
  },
  // Employees
  {
    id: 'emp-101',
    type: 'Employee',
    name: 'Ravi Kumar',
    employeeId: 'EMP1001',
    department: 'Operations',
    email: 'ravi.k@example.com',
    hostName: 'Sunita Reddy',
    hostDepartment: 'Supply Chain',
    reasonForVisit: 'Cross-department sync',
    selfieUrl: 'https://picsum.photos/seed/ravi-emp/100/100',
    checkInTime: new Date(new Date().setHours(9, 15, 0, 0)),
    status: 'Checked-in',
    location: { main: 'Corporate Office', sub: '1st Floor' },
  },
  {
    id: 'emp-102',
    type: 'Employee',
    name: 'Sonia Patel',
    employeeId: 'EMP1002',
    department: 'HR',
    hostName: 'Rajesh Gupta',
    hostDepartment: 'HR',
    reasonForVisit: 'Internal training session',
    selfieUrl: 'https://picsum.photos/seed/sonia-emp/100/100',
    checkInTime: new Date(new Date().setHours(10, 40, 0, 0)),
    checkOutTime: new Date(new Date().setHours(12, 0, 0, 0)),
    status: 'Checked-out',
    location: { main: 'Corporate Office', sub: '2nd Floor' },
  },
];
