
import type { MainLocation, Visitor, Department } from './types';

export const locations: MainLocation[] = [
  {
    id: 'corporate-office',
    name: 'Corporate Office',
    subLocations: [
      { id: '1st-floor', name: '1st Floor' },
      { id: '2nd-floor', name: '2nd Floor' },
      { id: '3rd-floor', name: '3rd Floor' },
    ],
  },
  {
    id: 'software-office',
    name: 'Software Office',
    subLocations: [],
  },
  {
    id: 'warehouse',
    name: 'Warehouse',
    subLocations: [],
  },
  {
    id: 'hostel',
    name: 'Hostel',
    subLocations: [],
  },
];

export const departments: Department[] = ['Supply Chain', 'Accounts', 'HR', 'Operations'];

export const receptionists = [
  {
    locationId: 'admin',
    locationName: 'Admin (All Locations)',
    email: 'admin@example.com',
    password: 'password123',
  },
  {
    locationId: 'corporate-office-1st-floor',
    locationName: 'Corporate Office - 1st Floor',
    email: 'reception.cop.1f@example.com',
    password: 'password123',
  },
  {
    locationId: 'corporate-office-2nd-floor',
    locationName: 'Corporate Office - 2nd Floor',
    email: 'reception.cop.2f@example.com',
    password: 'password123',
  },
  {
    locationId: 'corporate-office-3rd-floor',
    locationName: 'Corporate Office - 3rd Floor',
    email: 'reception.cop.3f@example.com',
    password: 'password123',
  },
];


export const mockVisitors: Visitor[] = [
  // Corporate Office - 1st Floor
  {
    id: '1',
    name: 'Ananya Singh',
    mobile: '9988776655',
    email: 'ananya.singh@example.com',
    hostName: 'Sunita Reddy',
    hostDepartment: 'Supply Chain',
    reasonForVisit: 'Vendor Meeting',
    selfieUrl: 'https://picsum.photos/seed/ananya/100/100',
    checkInTime: new Date(new Date().setHours(9, 30, 0, 0)),
    status: 'Checked-in',
    location: { main: 'Corporate Office', sub: '1st Floor' },
  },
  {
    id: '2',
    name: 'Sameer Jain',
    mobile: '9823456789',
    hostName: 'Sunita Reddy',
    hostDepartment: 'Supply Chain',
    reasonForVisit: 'Follow-up meeting',
    selfieUrl: 'https://picsum.photos/seed/sameer/100/100',
    checkInTime: new Date(new Date().setHours(14, 0, 0, 0)),
    status: 'Checked-in',
    location: { main: 'Corporate Office', sub: '1st Floor' },
  },
  {
    id: '3',
    name: 'Rahul Verma',
    mobile: '9123456780',
    hostName: 'Sunita Reddy',
    hostDepartment: 'Supply Chain',
    reasonForVisit: 'Delivery inquiry',
    selfieUrl: 'https://picsum.photos/seed/rahul/100/100',
    checkInTime: new Date(new Date().setHours(11, 45, 0, 0)),
    status: 'Checked-in',
    location: { main: 'Corporate Office', sub: '1st Floor' },
  },
  {
    id: '4',
    name: 'Neha Gupta',
    mobile: '9001234568',
    email: 'neha.gupta@example.com',
    hostName: 'Sunita Reddy',
    hostDepartment: 'Supply Chain',
    reasonForVisit: 'Partnership discussion',
    selfieUrl: 'https://picsum.photos/seed/neha/100/100',
    checkInTime: new Date(new Date().setHours(10, 0, 0, 0)),
    checkOutTime: new Date(new Date().setHours(11, 30, 0, 0)),
    status: 'Checked-out',
    location: { main: 'Corporate Office', sub: '1st Floor' },
  },
  {
    id: '5',
    name: 'Aditya Mehta',
    mobile: '9876543211',
    hostName: 'Sunita Reddy',
    hostDepartment: 'Supply Chain',
    reasonForVisit: 'Product demo',
    selfieUrl: 'https://picsum.photos/seed/aditya/100/100',
    checkInTime: new Date(new Date().setHours(16, 0, 0, 0)),
    status: 'Checked-in',
    location: { main: 'Corporate Office', sub: '1st Floor' },
  },

  // Corporate Office - 2nd Floor
  {
    id: '6',
    name: 'Priya Sharma',
    mobile: '9876543210',
    email: 'priya.sharma@example.com',
    hostName: 'Rajesh Gupta',
    hostDepartment: 'HR',
    reasonForVisit: 'Interview for a new role',
    selfieUrl: 'https://picsum.photos/seed/priya/100/100',
    checkInTime: new Date(new Date().setHours(10, 15, 0, 0)),
    status: 'Checked-in',
    location: { main: 'Corporate Office', sub: '2nd Floor' },
  },
  {
    id: '7',
    name: 'Kavita Iyer',
    mobile: '9112233445',
    email: 'kavita.iyer@example.com',
    hostName: 'Rajesh Gupta',
    hostDepartment: 'HR',
    reasonForVisit: 'Onboarding formalities',
    selfieUrl: 'https://picsum.photos/seed/kavita/100/100',
    checkInTime: new Date(new Date().setHours(9, 5, 0, 0)),
    checkOutTime: new Date(new Date().setHours(11, 20, 0, 0)),
    status: 'Checked-out',
    location: { main: 'Corporate Office', sub: '2nd Floor' },
  },
  {
    id: '8',
    name: 'Sneha Rao',
    mobile: '9444332211',
    email: 'sneha.rao@example.com',
    hostName: 'Rajesh Gupta',
    hostDepartment: 'HR',
    reasonForVisit: 'Joining documentation',
    selfieUrl: 'https://picsum.photos/seed/sneha/100/100',
    checkInTime: new Date(new Date().setHours(10, 45, 0, 0)),
    status: 'Checked-in',
    location: { main: 'Corporate Office', sub: '2nd Floor' },
  },
  {
    id: '9',
    name: 'Manish Tripathi',
    mobile: '9333221100',
    hostName: 'Rajesh Gupta',
    hostDepartment: 'HR',
    reasonForVisit: 'Compensation discussion',
    selfieUrl: 'https://picsum.photos/seed/manish/100/100',
    checkInTime: new Date(new Date().setHours(13, 0, 0, 0)),
    status: 'Checked-in',
    location: { main: 'Corporate Office', sub: '2nd Floor' },
  },
  {
    id: '10',
    name: 'Pooja Desai',
    mobile: '9222113344',
    email: 'pooja.desai@example.com',
    hostName: 'Rajesh Gupta',
    hostDepartment: 'HR',
    reasonForVisit: 'Final round interview',
    selfieUrl: 'https://picsum.photos/seed/pooja/100/100',
    checkInTime: new Date(new Date().setHours(15, 30, 0, 0)),
    status: 'Checked-in',
    location: { main: 'Corporate Office', sub: '2nd Floor' },
  },

  // Corporate Office - 3rd Floor
  {
    id: '11',
    name: 'Vikram Patel',
    mobile: '9001234567',
    hostName: 'Amit Desai',
    hostDepartment: 'Accounts',
    reasonForVisit: 'Invoice clarification',
    selfieUrl: 'https://picsum.photos/seed/vikram/100/100',
    checkInTime: new Date(new Date().setHours(12, 0, 0, 0)),
    checkOutTime: new Date(new Date().setHours(13, 30, 0, 0)),
    status: 'Checked-out',
    location: { main: 'Corporate Office', sub: '3rd Floor' },
  },
  {
    id: '12',
    name: 'Rohan Mehra',
    mobile: '9555667788',
    hostName: 'Amit Desai',
    hostDepartment: 'Accounts',
    reasonForVisit: 'Audit discussion',
    selfieUrl: 'https://picsum.photos/seed/rohan/100/100',
    checkInTime: new Date(new Date().setHours(15, 0, 0, 0)),
    status: 'Checked-in',
    location: { main: 'Corporate Office', sub: '3rd Floor' },
  },
  {
    id: '13',
    name: 'Deepak Shah',
    mobile: '9888776655',
    hostName: 'Amit Desai',
    hostDepartment: 'Accounts',
    reasonForVisit: 'Payment followup',
    selfieUrl: 'https://picsum.photos/seed/deepak/100/100',
    checkInTime: new Date(new Date().setHours(11, 10, 0, 0)),
    status: 'Checked-in',
    location: { main: 'Corporate Office', sub: '3rd Floor' },
  },
  {
    id: '14',
    name: 'Sonia Agarwal',
    mobile: '9777665544',
    email: 'sonia.agarwal@example.com',
    hostName: 'Amit Desai',
    hostDepartment: 'Accounts',
    reasonForVisit: 'Quarterly review',
    selfieUrl: 'https://picsum.photos/seed/sonia/100/100',
    checkInTime: new Date(new Date().setHours(14, 30, 0, 0)),
    checkOutTime: new Date(new Date().setHours(16, 0, 0, 0)),
    status: 'Checked-out',
    location: { main: 'Corporate Office', sub: '3rd Floor' },
  },
  {
    id: '15',
    name: 'Alok Nath',
    mobile: '9666554433',
    hostName: 'Amit Desai',
    hostDepartment: 'Accounts',
    reasonForVisit: 'Financial reporting',
    selfieUrl: 'https://picsum.photos/seed/alok/100/100',
    checkInTime: new Date(new Date().setHours(16, 30, 0, 0)),
    status: 'Checked-in',
    location: { main: 'Corporate Office', sub: '3rd Floor' },
  },

  // Other locations
  {
    id: '16',
    name: 'Arjun Kumar',
    mobile: '9123456789',
    hostName: 'Sanjay Verma',
    hostDepartment: 'Operations',
    reasonForVisit: 'Scheduled Maintenance',
    selfieUrl: 'https://picsum.photos/seed/arjun/100/100',
    checkInTime: new Date(new Date().setHours(11, 0, 0, 0)),
    status: 'Checked-in',
    location: { main: 'Warehouse', sub: '1st Floor' },
  },
];
