
import type { MainLocation, Visitor, Department } from './types';

export const locations: MainLocation[] = [
  {
    id: 'corporate-office',
    name: 'Corporate Office',
    subLocations: [
      { id: '1st-floor', name: '1st Floor' },
      { id: '2nd-floor', name: '2nd Floor' },
      { id: '3rd-floor', name: '3rd Floor' },
    ],
  },
  {
    id: 'software-office',
    name: 'Software Office',
    subLocations: [],
  },
  {
    id: 'warehouse',
    name: 'Warehouse',
    subLocations: [{ id: '1st-floor', name: '1st Floor' }],
  },
  {
    id: 'hostel',
    name: 'Hostel',
    subLocations: [
      { id: '1st-floor', name: '1st Floor' },
      { id: '2nd-floor', name: '2nd Floor' },
      { id: '3rd-floor', name: '3rd Floor' },
    ],
  },
];

export const departments: Department[] = ['Supply Chain', 'Accounts', 'HR', 'Operations'];

export const receptionists = [
  {
    locationId: 'corporate-office-1st-floor',
    locationName: 'Corporate Office - 1st Floor',
    email: 'reception.cop.1f@example.com',
    password: 'password123',
  },
  {
    locationId: 'corporate-office-2nd-floor',
    locationName: 'Corporate Office - 2nd Floor',
    email: 'reception.cop.2f@example.com',
    password: 'password123',
  },
  {
    locationId: 'corporate-office-3rd-floor',
    locationName: 'Corporate Office - 3rd Floor',
    email: 'reception.cop.3f@example.com',
    password: 'password123',
  },
];


export const mockVisitors: Visitor[] = [
  {
    id: '1',
    name: 'Priya Sharma',
    mobile: '9876543210',
    email: 'priya.sharma@example.com',
    hostName: 'Rajesh Gupta',
    hostDepartment: 'HR',
    reasonForVisit: 'Interview for a new role',
    selfieUrl: 'https://picsum.photos/seed/priya/100/100',
    checkInTime: new Date(new Date().setHours(10, 15, 0, 0)),
    status: 'Checked-in',
    location: { main: 'Corporate Office', sub: '2nd Floor' },
  },
  {
    id: '2',
    name: 'Arjun Kumar',
    mobile: '9123456789',
    hostName: 'Sanjay Verma',
    hostDepartment: 'Operations',
    reasonForVisit: 'Scheduled Maintenance',
    selfieUrl: 'https://picsum.photos/seed/arjun/100/100',
    checkInTime: new Date(new Date().setHours(11, 0, 0, 0)),
    status: 'Checked-in',
    location: { main: 'Warehouse', sub: '1st Floor' },
  },
  {
    id: '3',
    name: 'Ananya Singh',
    mobile: '9988776655',
    email: 'ananya.singh@example.com',
    hostName: 'Sunita Reddy',
    hostDepartment: 'Supply Chain',
    reasonForVisit: 'Vendor Meeting',
    selfieUrl: 'https://picsum.photos/seed/ananya/100/100',
    checkInTime: new Date(new Date().setHours(9, 30, 0, 0)),
    status: 'Checked-in',
    location: { main: 'Corporate Office', sub: '1st Floor' },
  },
  {
    id: '4',
    name: 'Vikram Patel',
    mobile: '9001234567',
    hostName: 'Amit Desai',
    hostDepartment: 'Accounts',
    reasonForVisit: 'Invoice clarification',
    selfieUrl: 'https://picsum.photos/seed/vikram/100/100',
    checkInTime: new Date(new Date().setHours(12, 0, 0, 0)),
    checkOutTime: new Date(new Date().setHours(13, 30, 0, 0)),
    status: 'Checked-out',
    location: { main: 'Corporate Office', sub: '3rd Floor' },
  },
  {
    id: '5',
    name: 'Sameer Jain',
    mobile: '9823456789',
    hostName: 'Sunita Reddy',
    hostDepartment: 'Supply Chain',
    reasonForVisit: 'Follow-up meeting',
    selfieUrl: 'https://picsum.photos/seed/sameer/100/100',
    checkInTime: new Date(new Date().setHours(14, 0, 0, 0)),
    status: 'Checked-in',
    location: { main: 'Corporate Office', sub: '1st Floor' },
  },
  {
    id: '6',
    name: 'Kavita Iyer',
    mobile: '9112233445',
    email: 'kavita.iyer@example.com',
    hostName: 'Rajesh Gupta',
    hostDepartment: 'HR',
    reasonForVisit: 'Onboarding formalities',
    selfieUrl: 'https://picsum.photos/seed/kavita/100/100',
    checkInTime: new Date(new Date().setHours(9, 5, 0, 0)),
    checkOutTime: new Date(new Date().setHours(11, 20, 0, 0)),
    status: 'Checked-out',
    location: { main: 'Corporate Office', sub: '2nd Floor' },
  },
  {
    id: '7',
    name: 'Rohan Mehra',
    mobile: '9555667788',
    hostName: 'Amit Desai',
    hostDepartment: 'Accounts',
    reasonForVisit: 'Audit discussion',
    selfieUrl: 'https://picsum.photos/seed/rohan/100/100',
    checkInTime: new Date(new Date().setHours(15, 0, 0, 0)),
    status: 'Checked-in',
    location: { main: 'Corporate Office', sub: '3rd Floor' },
  },
  {
    id: '8',
    name: 'Sneha Rao',
    mobile: '9444332211',
    email: 'sneha.rao@example.com',
    hostName: 'Rajesh Gupta',
    hostDepartment: 'HR',
    reasonForVisit: 'Joining documentation',
    selfieUrl: 'https://picsum.photos/seed/sneha/100/100',
    checkInTime: new Date(new Date().setHours(10, 45, 0, 0)),
    status: 'Checked-in',
    location: { main: 'Corporate Office', sub: '2nd Floor' },
  },
];
